# Welcome to Jekyll!
#

# Site settings
title: MattyKeene
description: |
  Software Developer. Tinkerer. Lover of the outdoors.
owner: Matt Keene
# first_published: # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: /mattykeene # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  github: https://github.com/mathewkeene22
  linkedin-square: https://linkedin.com/in/mathewkeene
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  instagram: https://www.instagram.com/matty_keene
  email: mailto:mathewkeene22@gmail.com
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
sass:
  sass_dir:
  style: compressed

slideshow:
    width: 150
    height: 100

theme: jekyll-theme-cayman
